version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    env_file: ./db/.env

  code:
    build: .
    volumes:
      - .:/api
    ports:
      - "8010:8010"
    depends_on:
      - db
    command: python3 api/waiter.py
